camel:
  springboot:
    main-run-controller: true

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: app.log

camelApp:
  startRoute: "receiver"
  folders:
    prepareDir: "prepare"
    workDir: "work"
    dataDir: "data"
    doneDir: "done"
    invalidDir: "invalid"
